var STRINGS_ES ={
//termes Communs

      "isYearMonthDateFormat"                                   : "true",
      "appName"                                                 : "Sage Customer View",

      "welcome"                                                 : "Bienvenido",
      "welcomeMessage"                                          : "Conéctate por favor",
      
      "customerDetailSectionTitle"                              : "Información del cliente",
      "customerDetail"                                          : "Información del cliente",
      "accountingType"                                          : "Tipo de contabilidad",
      
      "operatingCompanyName"                                    : "Nombre Empresa",
      "operatingCompanyShortName"                               : "Nombre corto",
      
      "customerAddress"                                         : "Dirección del cliente",
      "resourceUnavailable"                                     : "No disponible.",
      "kpiUnavailable"                                          : "Indicador no diponible.",
      "kpiExecutionError"                                       : "Error al ejecutar el indicador.",
      
      "welcome.labelAlreadyRegistered"                          : "¿Ya eres usuario?",
      "welcome.connectButton"                                   : "Conéctate",
      "welcome.loading"                                         : "Cargando",
      "welcome.videoTitle"                                      : "Consulta la situación de tu negocio.",
      "welcome.doYouWantToKnowMore"                             : "¿Quieres más información? haz clic aquí",
      "welcome.testButton"                                      : "Prueba nuestra aplicación",
      "welcome.accountButton"                                   : "Crea una cuenta",
      "welcome.contactButton"                                   : "Contáctanos",
      "welcome.tryContentText"                                  : "Toda la información de tus Clientes y de las Ventas en la palma de tu mano.",
     
      "backgroundColor"                                         : "Color de fondo de la aplicación",
      "i18n"                                                    : "i18n Strings",
      "style"                                                   : "Estilo personalizado",
      
      "login.loading"                                           : "Cargando...",
      "login.loading.fromRetry"                                 : "Esperando la conexión",
      "login.loading.retry"                                     : "Reconexión ...",
      "login.loading.retryWin"                                  : "descarga de datos",
      "login.signingoff"                                        : "Cerrar sesión",
      
      "sync.dataFreshness"                                      : "Datos actualizados {{s0}}",
      "sync.dataExpired"                                        : "Los nuevos datos disponibles!",
      
      "appbar.cmdSync"                                          : "Cargando",
      "appbar.cmdSignIn"                                        : "Ingresar",
      "appbar.cmdSignOff"                                       : "Firmar",
      "appbar.cmdToggleDebug"                                   : "Alternar consola",
      "appbar.cmdEnv"                                           : "Seleccionar Entorno",
      "appbar.cmdFavorite"                                      : "Favorito",
      "appbar.cmdUnfavorite"                                    : "Desmarcar Favorito",
      "appbar.cmdRemove"                                        : "Eliminar",
      "appbar.cmdAccept"                                        : "Aceptar",
      "appbar.cmdEdit"                                          : "Editar",
      "appbar.cmdSave"                                          : "Guardar",
      "appbar.cmdRestore"                                       : "Restaurar",
      "appbar.cmdPeriod1"                                       : "Primer período",
      "appbar.cmdPeriod1Only"                                   : "Período",
      "appbar.cmdPeriod2"                                       : "Segundo período",
      "appbar.cmdGlobalFavoriteButton"                          : "Favorito",
      "appbar.cmdGlobalUnFavoriteButton"                        : "Desmarcar Favorito",
      "appbar.cmdEnvDev"                                        : "Desarrollo",
      "appbar.cmdEnvPreprod"                                    : "Preproducción",
      "appbar.cmdOpenCharms"                                    : "Configuración",
      "appbar.cmdAdd"                                           : "Añadir",
      "appbar.cmdRefresh"                                       : "Refrescar",
      "appbar.cmdOtherPrompts"                                  : "Otros mensajes",
      
      "charms.settings"                                         : "Preferencias",
      "charms.about.title"                                      : "Acerca de",
      "charms.about.mainTitle"                                  : "Acerca de",
      "charms.about.version"                                    : "Versión",
      "charms.about.contactus"                                  : "Contáctanos",
      "charms.about.email"                                      : "hermesteam@sage.com",
      "charms.about.aboutText"                                  : "Este producto es propiedad de Sage (UK) Limited, una sociedad de responsabilidad limitada registrada en Inglaterra y Gales con número de identificación fiscal 01045967 y domicilio social en North Park, Newcastle upon Tyne, NE13 9AA.  Tenemos otras direcciones comerciales. Si deseas más información sobre nuestras direcciones comerciales, ponte en contacto con nosotros. Nuestro CIF es GB555909605.",
      "charms.about.privacyStatement"                           : "Declaración de privacidad",
      "charms.about.privacyStatementLink"                       : "http://www.sage.fr",
      "charms.about.cguTitle"                                   : "Ver términos y condiciones",
      "charms.deconnection"                                     : "Cerrar sesión",
      "charms.support"                                          : "Asistencia",
      "charms.supportLink"                                      : "/webresources/services/public/forms/index.html#/app/Sage_Customer_View/type/contact/erp/murano/country/es",
      "charms.privacyStatement"                                 : "Política de privacidad",
      "charms.privacyStatementLink"                             : "/QueryService/doc/SageDataManager/es/CGU_Sage.pdf ",
      
      "appbar.flyout.save"                                      : "Guardar",
      "appbar.flyout.saveAs"                                    : "Guardar como",
      
      "settings.theming.title"                                  : "Temas",
      "settings.title"                                          : "Preferencias",
      "settings.deconnection.button"                            : "Cerrar sesión",
      "settings.deconnection.text"                              : "Desconéctate de la aplicación Sage Customer View.",
      "settings.deconnection.msg"                               : "Te desconectarás de la aplicación Sage Customer View.",
      "settings.theming.text"                                   : "Cambiar imagen de fondo y el tema.",
      "settings.deconnection.title"                             : "Cerrar sesión",
      
      "dev.debugconsole.title"                                  : "Consola de depuración",
      "dev.debugconsole.text"                                   : "Activar o desactivar la consola de depuración.",
      "dev.environment.title"                                   : "Entorno",
      "dev.environment.text"                                    : "Cambiar el entorno de la aplicación.",
      
      "dialog.cancel"                                           : "Cancelar",
      "dialog.accept"                                           : "Aceptar",
      "dialog.removeKpi.txt"                                    : "Este indicador no se puede quitar",
      
      "appbar.errordialog.close"                                : "Cerrar",
      "appbar.errordialog.retry"                                : "Reintentar",
      "appbar.removeKpiDialog.msg.start"                        : "¿Confirmar la eliminación de ",
      "appbar.removeKpiDialog.msg.end"                          : " ?",
      
      "flyout.save.title"                                       : "Nuevo título",
      
      "modules.semanticZoomCustomer"                            : "Vista agrupada de todos los clientes",
      "modules.semanticZoomCustomer.title"                      : "Mis clientes",
      "modules.semanticZoomCustomer.datasource"                 : "Fuente de datos",
      "modules.semanticZoomCustomer.zoomindetail"               : "Acercar mosaico",
      "modules.semanticZoomCustomer.zoomindetail.template"      : "Plantilla Acercar mosaico",
      "modules.semanticZoomCustomer.zoominheader"               : "Acercar mosaico de cabeceras",
      "modules.semanticZoomCustomer.zoominheader.template"      : "Plantilla Acercar cabecera",
      "modules.semanticZoomCustomer.zoomoutdetail"              : "Alejar mosaico",
      "modules.semanticZoomCustomer.zoomoutdetail.template"     : "Plantilla Alejar mosaico",
      "modules.semanticZoomCustomer.zoomoutheader"              : "Alejar cabecera",
      "modules.semanticZoomCustomer.zoomoutheader.template"     : "Plantilla Alejar cabecera",
      "modules.semanticZoomCustomer.sort"                       : "Filtros",
      "modules.semanticZoomCustomer.sort.alpha"                 : "Ordenación alfabética",
      "modules.semanticZoomCustomer.sort.accountingType"        : "Tipo de Cuenta",
      "modules.semanticZoomCustomer.sort.zipcode"               : "Código postal",

      "modules.customerList"                                    : "Lista de Clientes",
      "modules.customerList.preview"                            : "Vista previa de cliente",
      "modules.customerList.preview.template"                   : "Plantilla Vista previa de cliente",
      "modules.customerList.detail"                             : "Detalle Cliente",
      "modules.customerList.detail.template"                    : "Plantilla Detalles de cliente",
      "modules.customerList.navigation"                         : "Explorar Clientes",
      "modules.customerList.semanticzoom"                       : "Explorar Detalles de Cliente",
      "modules.customerList.title"                              : "Mis Clientes",
      
      "modules.salesDocumentCustomer.title"                     : "Documentos",
      "modules.semanticZoomSalesDocumentCustomer.title"         : "Documentos del cliente",
      
      "modules.invoiceList"                                     : "Lista de facturas",
      "modules.invoiceList.preview"                             : "Vista previa de factura",
      "modules.invoiceList.preview.query"                       : "Consultar lista de facturas",
      "modules.invoiceList.preview.maxResult"                   : "Núm. máx. de facturas por visualizar",
      "modules.invoiceList.preview.template"                    : "Plantilla Vista previa de factura",
      "modules.invoiceList.detail"                              : "Detalle de factura",
      "modules.invoiceList.detail.template"                     : "Plantilla Detalles de factura",
      
      "modules.quoteList.detail"                                : "Detalle Oferta",
      "modules.quoteList.detail.template"                       : "Plantilla Detalle Oferta",
      "modules.quoteList.navigation"                            : "Explorar Oferta",
      "modules.quoteList.semanticzoom"                          : "Explorar Detalle Oferta",
      
      "modules.invoiceList.navigation"                          : "Explorar Factura",
      "modules.invoiceList.semanticzoom"                        : "Explorar Detalle Factura",

      "modules.semanticZoomInvoice.title"                       : "Mis Facturas",
      "modules.invoiceList.title"                               : "Mis Facturas",
      "modules.salesDocumentCustomer"                           : "Documento de Ventas al Cliente",
      "modules.orderList.title"                                 : "Mis Pedidos",
      "modules.semanticZoomOrder.title"                         : "Mis Pedidos",
      "modules.semanticZoomQuote.title"                         : "Mis Ofertas",
      "modules.quoteList.title"                                 : "Mis Ofertas",
      "modules.semanticZoomDelivery.title"                      : "Mis Albaranes",
      "modules.deliveryList.title"                              : "Mis Albaranes",
      
      "dashboards.shortcuts"                                    : "Accesos directos a Indicadores",
      "dashboardhome"                                           : "Mi Actividad",
      "dashboardcustomer"                                       : "Biblioteca de Indicadores",
      
      "modules.semanticZoomDashboardhome.title"                 : "Mi Actividad",
      "modules.semanticZoomDashboardcustomer.title"             : "Biblioteca de indicadores",
      "modules.salesDocumentCustomer.noDocument"                : "No hay documentos para este cliente",
      "modules.salesDocumentCustomer.connectionRequired"        : "Conexión requerida para acceder a los documentos",
      "modules.customerList.noCustomer"                         : "No hay Cliente",
      "modules.documents.noDocument"                            : "No hay Documento",
      
      "roles.salesManager"                                      : "Director de ventas",
      "roles.salesRep"                                          : "Comercial",
      
      "prompts.period1"                                         : "Primer período",
      "prompts.period2"                                         : "Segundo período",
      "prompts.enablePeriod"                                    : "Habilitar período",
      "prompts.customPeriod"                                    : "Ejercicio actual",
      "prompts.allDates"                                        : "Todas las fechas",
      "prompts.allValues"                                       : "Todos los valores",
      "prompts.checkAllValues"                                  : "Seleccionar todos",
      "prompts.unCheckAllValues"                                : "Desmarcar todos",
      "prompts.applyChanges"                                    : "Aplicar",
      "prompts.emptyValue"                                      : "(Vacío)",
      "prompts.notLimit"                                        : "Ver todo",
      
      "kpi.kpiNotAvailable"                                     : "No disponible",
      "kpi.notEnoughData"                                       : "No hay suficientes datos",
      "kpi.kpiShortcutDeleted"                                  : "Indicador borrado",
      
      "search.noresult"                                         : "Ningún resultado coincide con tu búsqueda.",
      "search.resultfor"                                        : "Resultados para",
      "search.filter.all"                                       : "Todos",
      "sharing.title"                                           : "Difusión de la información",
      "sharing.description"                                     : "Se adjunta información sobre",
      
      "navbar.cmdGlobalMyInvoicesButton"                        : "Mis Facturas",
      "navbar.cmdGlobalMyCustomersButton"                       : "Mis Clientes",
      "navbar.cmdGlobalMyDashboardButton"                       : "Mi Panel",
      "navbar.cmdGlobalMyOrdersButton"                          : "Mis Pedidos",
      "navbar.cmdGlobalMyDeliveriesButton"                      : "Mis Albaranes",
      "navbar.cmdGlobalMyQuotesButton"                          : "Mis Ofertas",
      "navbar.cmdGlobalMyIndicatorsButton"                      : "Mis Indicadores",
      "navbar.cmdGlobalCollaborateurExpensesButton"             : "Mis Gastos",
      "_navbar.cmdGlobalCollaborateurExpensesButton"            : "Mis Gastos",
      "navbar.cmdGlobalValidateurExpensesButton"                : "Validar gastos",
      
      "kpiDetail.periodsTitleText"                              : "Período de análisis {{#if periodNumber}}(P{{periodNumber}}){{/if}}",
      "kpiDetail.promptsTitleText"                              : "Parámetros",
      "kpiDetail.descriptionTitleText"                          : "Comentarios",
      "kpiDetail.fromText"                                      : "Desde",
      "kpiDetail.toText"                                        : "A",
      "kpiDetail.periodCompareText"                             : "Período comparativo (P{{periodNumber}})",
      "kpiDetail.firstSectionTitle"                             : "Resumen",
      "kpiDetail.secondSectionTitle"                            : "Detalle",
      "KpiDetail.invalidPeriodMB.msg"                           : "¡La fecha de inicio debe ser menor que la fecha fin!",
      "KpiDetail.invalidPeriodMB.title"                         : "Periodo personalizado",
      "salesDocument.designationHeader"                         : "Descripción",
      "salesDocument.quantityHeader"                            : "Cantidad",
      "salesDocument.unitPriceHeader"                           : "Precio por unidad",
      "salesDocument.totalHeader"                               : "Total",
      "salesDocument.discountHeader"                            : "Descuento",

      "module.quote.title"                                      : "Oferta",
      "module.quote.documentname"                               : "Oferta",
      "module.delivery.title"                                   : "Entrega",
      "module.delivery.documentname"                            : "Entrega",
      "module.invoice.title"                                    : "Factura",
      "module.invoice.documentname"                             : "Factura",
      "module.document.title"                                   : "Documento",
      "module.document.documentname"                            : "Documento",
      "module.order.title"                                      : "Orden",
      "module.order.documentname"                               : "Orden",
      "module.customer.title"                                   : "Clientes",
      "module.quote.totalTax"                                   : "Total impuestos",
      "module.share.customer"                                   : "Cliente",
      "module.share.amountwithoutvat"                           : "Importe neto",
      "module.share.customerReference"                          : "Referencia del cliente",
      "module.share.customerInformations"                       : "Información del cliente",
      "module.customer"                                         : "Cliente",
      "module.totalwithoutvat"                                  : "Importe neto",
      "module.shippingcost"                                     : "Importe portes",
      "module.totalwithoutvatnet"                               : "Base Imponible",
      "module.discount"                                         : "Descuento",
      "module.totalwithvat"                                     : "Importe Líquido",
      "module.modelregulation"                                  : "Modo de entrega",
      "module.pricinglist"                                      : "Tarifa",
      "module.payingauthority"                                  : "Entidad pagadora",
      "module.dueterm"                                          : "Plazo",
      "module.termamount"                                       : "Cantidad",
      "module.payingmethod"                                     : "Método de pago",
      "module.deliverydate"                                     : "Fecha de entrega",
      "module.expedition"                                       : "Método de envío",
      "module.expensechargedamount"                             : "Envío",
      "module.depotDeliveryCustomer"                            : "Lugar de entrega",
      "module.depot"                                            : "Depósito",
      "module.totaltax"                                         : "Total impuestos",
      "module.from"                                             : "Fecha",
      "module.expenseList.title"                                : "Gasto",
      "modules.expenseList.title"                               : "Gastos",
      "modules.expenseLineList.title"                           : "Líneas de gastos",
      "modules.semanticZoomExpense.title"                       : "Gastos",
      "modules.expenseLine.form.newTitle"                       : "Nueva línea de gastos",
      "modules.expenseLine.form.editTitle"                      : "Editar línea de gastos",
      "module.expenseList.form.submit"                          : "Presentar",
      "module.expenseLineList.form.submit"                      : "Presentar",
      "module.expenseLineList.form.reset"                       : "Nuevo gasto",
      "module.expenseLineList.form.attachedFile"                : "Adjuntar un archivo",
      "module.expenseLineList.form.capture"                     : "Capturar la pantalla",
      "module.expenseLineList.form.pick"                        : "Seleccionar una imagen",
      "module.expenseLineList.form.insert"                      : "Insertar una imagen",
      "module.expenseLineList.form.selectMethodePicture"        : "Elegir método de inserción",
      "modules.uploadZone.form.editTitle"                       : "Justificative",
      "module.expense.form.title"                               : "Título",
      "module.expense.form.status"                              : "Estado",
      "module.expense.form.description"                         : "Descripción",
      "module.expenses.hubCollaborator"                         : "Mis Gastos",
      "modules.expenseListProgress.title"                       : "Mis Gastos pendientes",
      "modules.semanticZoomExpenseProgress.title"               : "Mis Gastos pendientes",
      "modules.expenseListWaiting.title"                        : "Mis Gastos esperados",
      "modules.semanticZoomExpenseWaiting.title"                : "Mis Gastos esperados",
      "modules.expenseListTerminated.title"                     : "Mis Gastos pagados",
      "modules.semanticZoomExpenseTerminated.title"             : "Mis Gastos pagados",
      "modules.expenseFiche.title"                              : "Mis Gastos",
      "modules.expenseFiche.reference"                          : "Referencia",
      "modules.expenseFiche.date"                               : "Fecha",
      "modules.expenseFiche.label"                              : "Etiqueta",
      "modules.expenseFiche.analyticalProject"                  : "Analítica",
      "modules.expenseFiche.comment"                            : "Comentario",
      "modules.expenseFiche.client"                             : "Cliente",
      "modules.expenseFiche.realTotal"                          : "Suma total",
      "modules.expenseFiche.reimbursedTotal"                    : "Total reembolsado",
      "modules.expenseFiche.status"                             : "Estado",
      "modules.expenseFiche.addExpenseLine"                     : "Añadir línea de gasto",
      "modules.expenseFiche.removeExpenseLine"                  : "Eliminar línea de gasto",
      "modules.expenselines.title"                              : "Mis líneas de gasto",
      
      "expenses.dateHeader"                                     : "Fecha",
      "expenses.depenseHeader"                                  : "Categoría",
      "expenses.labelHeader"                                    : "Etiqueta",
      "expenses.realAmountHeader"                               : "Importe total",
      "expenses.reimbursedAmountHeader"                         : "Importe total reembolsado",
      
      "addFavorite"                                             : "Añadir Favorito",
      
      "semanticZoom.sort.other"                                 : "Otros",
      "semanticZoom.kpi.sort.type.synthesis"                    : "Síntesis",
      "semanticZoom.kpi.sort.type.evolution"                    : "Evolución",
      "semanticZoom.kpi.sort.type.podium"                       : "Podio",
      "semanticZoom.kpi.sort.type.number"                       : "Número",
      "semanticZoom.kpi.sort.type.compare"                      : "Comparar",
      "semanticZoom.kpi.sort.category.clients"                  : "Mis Clientes",
      "semanticZoom.kpi.sort.category.employee"                 : "Delegado de ventas",
      "semanticZoom.kpi.sort.category.salesrep"                 : "Delegado de ventas",
      "semanticZoom.kpi.sort.category.quotes"                   : "Ofertas",
      "semanticZoom.kpi.sort.category.order"                    : "Pedido",
      "semanticZoom.kpi.sort.category.total_turnover"           : "Facturación",
      "semanticZoom.kpi.sort.category.glb_total_turnover"       : "Facturación total",
      "semanticZoom.kpi.sort.category.sellsrep"                 : "Delegado de ventas",
      "semanticZoom.kpi.sort.category.delivery"                 : "Mis Albaranes",
      "semanticZoom.kpi.sort.category.product"                  : "Producto",
      "semanticZoom.kpi.changingFavoriteStatus"                 : "Cambiado estado de favorito...",
      "semanticZoom.kpi.sort.univers.gescom"                    : "ERP",
      "semanticZoom.kpi.sort.univers.compta"                    : "Contabilidad",
      "semanticZoom.customer.informations"                      : "Información",
      
      "kpiDetail.loading"                                       : "Calculando Indicador...",
      
      "semanticZoom.processing"                                 : "Procesando...",
      
      "dataviz.limit.otherGroupLabel"                           : "Otros",
      
      "errorMessage.cannotSaveKPI"                              : "Imposible guardar tu indicador.",
      "errorMessage.noConnectionAvailable"                      : "No estás conectado a Internet. Para usar esta función conéctate a Internet y vuelve a intentarlo.",
      "errorMessage.serverNotAvailable"                         : "El servidor está fuera de servicio por mantenimiento. Por favor, inténtalo de nuevo más tarde.",
      "errorMessage.serverNotReachable"                         : "El servidor no está accesible",
      "errorMessage.noServerResponse"                           : "No se ha obtenido ninguna respuesta del servidor.",
      "errorMessage.unauthorized"                               : "No estás autorizado para realizar esta solicitud. Verifica las credenciales de tu proxy.",
      "errorMessage.status.unauthorized"                        : "No estás autorizado para realizar esta solicitud. Compruebe sus credenciales de proxy.",
      "errorMessage.status.forbidden"                           : "No dispones de permisos para acceder a esta aplicación.",
      "errorMessage.status.not.found"                           : "En mantenimiento. Por favor vuelvelo a intentar en unos minutos.",
      "errorMessage.status.unreachable"                         : "No hay acceso al servidor. Por favor vuelve a intentarlo de nuevo en unos minutos.",
      "errorMessage.status.internal.server.error"               : "Se ha producido un error de trigger. Por favor, informa a Sage de esta cuestión tan pronto como sea posible.",
      "errorMessage.status.bad.request"                         : "No puedes acceder a esta aplicación. Por favor, contacta con el administrador de tu empresa para obtener acceso",
      "errorMessage.text.no.app.role"                           : "Por favor, contacta con el administrador de tu empresa para obtener acceso",
      "errorMessage.text.user.not.found"                        : "Lo sentimos pero aún no tienes acceso a Sage Customer View",
      "errorMessage.text.tenant.disabled"                       : "Lo sentimos pero ha caducado el contrato. Por favor contacta con Sage para su renovación.",
      "errorMessage.text.authentication.header.not.found"       : "El inicio de sesión ha fallado. Por favor inténtalo de nuevo o contacta con tu administrador.",
      "errorMessage.text.authentication.null.session"           : "El inicio de sesión ha fallado debido a un fallo de comunicación entre nuestro servidor de autenticación y esta aplicación",
      "errorMessage.text.authentication.invalid.session.format" : "El inicio de sesión ha fallado debido a un error de cifrado durante la autorización.",
      "errorMessage.text.bad.authentication.header"             : "El inicio de sesión ha fallado. Tu cuenta de usuario no corresponde a una cuenta de cliente",
      "errorMessage.text.token.already.outdated"                : "Nuestro servidor no es capaz de dar acceso a ningún usuario debido a un error de configuración.",
      "errorMessage.status.timeout"                             : "No ha sido posible iniciar tu sesión debido a una conexión lenta. Por favor, inténtalo de nuevo.",
      
      "sync.message.authenticate"                               : "Autorizando...",
      "sync.message.loadingAppDefinition"                       : "Cargando definición de aplicación",
      "sync.message.synchronisationOk"                          : "Aceptar sincronización",
      "sync.message.errorGettingData"                           : "La sincronización ha fallado (al obtener datos)",
      "sync.message.errorCancel"                                : "Error. Cancelar",
      "sync.message.errorOffline"                               : "La sincronización ha fallado (fuera de línea)",
      
      "resourceStorage.message.loadingResource"                 : "Cargando recurso",
      
      "kpiRequester.message.loading"                            : "Cargando",
      "kpiRequester.message.dashboard"                          : "Panel",
      
      "pivotTable.noDataText"                                   : "No hay datos disponibles",
      
      "hermes.notSync"                                          : "Sin sincronizar",
      "hermes.online"                                           : "Conectado",
      "hermes.youareonline"                                     : "Estás conectado",
      "hermes.offline"                                          : "Desconectado",
      "hermes.youareoffline"                                    : "Estás desconectado",
      "hermes.form.required"                                    : "Este campo es obligatorio",
      
      "errmess.noTemplate"                                      : "No se ha encontrado la plantilla para el módulo: {{moduleId}}",
      "errmess.noKpiDetail"                                     : "No hay información disponible en este indicador",
      
      "dashboardexpense"                                        : "Mis estadísticas",
      "_dashboardexpenseComment"                                : "Mis estadísticas",
      
      "module.expense.noneExpense"                              : "Panel de gastos",
      "_module.expense.noneExpense"                             : "Panel de gastos",
      
      "expenses.errmess.cannotDelete"                           : "No se puede eliminar el elemento.",
      "expenses.errmess.cannotCreateUpdate"                     : "Error creando o modificando",
      "expenses.errmess.loadError"                              : "Error durante la carga",
      "expenses.errmess.loadingImg"                             : "Error cargando imagen",

//termes IOS
      "msgbox.titleErrorSync"                                   :"Sincronización",
      "msgbox.messageErrorSync"                                 :"Por favor, inicia la sesión si deseas sincronizar tus datos",
      
      "welcome.doYouWantToKnowMoreInfo"                         :"¿Quieres más información? ",
      "welcome.clickHere"                                       :"haz clic aquí",
      
      "customer.tab.customer"                                   :"Cliente",
      "customer.tab.dashboard"                                  :"Indicadores",
      "customer.informations"                                   :"Informaciones",
      "customer.tab.documents"                                  :"Documentos",
      
      "titlebar.synchronize"                                    :"Sincronizar",
      "titlebar.agrandir"                                       :"Maximizar",
      "titlebar.reduire"                                        :"Minimizar",
      "titlebar.apropos"                                        :"Acerca de",
      
      "home.allKPI"                                             :"Ver todos los Indicadores",
      "home.allCustomers"                                       :"Ver todos los Clientes",
      "home.allInvoices"                                        :"Ver todas las Facturas",
      "home.allOrders"                                          :"Ver todos los Pedidos",
      "home.allDeliveries"                                      :"Ver todos los Albaranes de entrega",
      "home.allQuotations"                                      :"Ver todas las Ofertas",
      "home.addFavoriteCustomer"                                :"Añadir un Cliente a favoritos",
      "home.addFavoriteKPIToFavoris"                            :"Añadir un Indicador a favoritos",
      
      "search"                                                  :"Búsqueda",
      
      "message.alert"                                           :"Alerta",
      "message.expiredSession"                                  :"Tu sesión ha expirado. Debe volver a conectarse",
      "message.noConnection"                                    :"Sin conexión. La conexión de red no está disponible",
      "message.connectionFailed"                                :"La conexión ha fallado. Comprueba la validez de su token.",
      
      "kpi.name"                                                :"Nombre de Indicador",
      "kpi.detail"                                              :"Detalle indicador",
      "kpi.setName"                                             :"Introduce un nombre para el Indicador antes de guardarlo.",

      "month.Jan"                                               :"enero",
      "month.Feb"                                               :"febrero",
      "month.Mar"                                               :"marzo",
      "month.Apr"                                               :"abril",
      "month.May"                                               :"mayo",
      "month.Jun"                                               :"junio",
      "month.Jul"                                               :"julio",
      "month.Aug"                                               :"agosto",
      "month.Sep"                                               :"septiembre",
      "month.Oct"                                               :"octubre",
      "month.Nov"                                               :"noviembre",
      "month.Dec"                                               :"diciembre",
      
      "confirm.yes"                                             :"Si",
      "confirm.no"                                              :"No",

      "periodpicker.and"                                        : "y"

//termes Windows 8


};